/*******************************************************/
/**  Autogenerated cart tree for cmu_viH_pos    */
/**  from result    */
/*******************************************************/
extern "C"{
DEF_STATIC_CONST_VAL_STRING(val_0000,"fn");
}