/*******************************************************/
/**  Autogenerated phoneset trees for cmu_viH    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset cmu_viH_phoneset;


static const char * const cmu_viH_featnames[] = {
 "clst",
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 "asp",
 "nuk",
 NULL };

static const char * const cmu_viH_phonenames[] = {
 "pau",
 "uowfi",
 "ieefu",
 "uoori",
 "iowsi",
 "uyeex",
 "ieeju",
 "uyees",
 "uyeej",
 "uyeer",
 "uyeef",
 "iuwxa",
 "uoosi",
 "uowsi",
 "ieesu",
 "yeesu",
 "ieeru",
 "iaasy",
 "uowju",
 "iaasu",
 "iuowf",
 "uooxi",
 "ieexu",
 "uowxi",
 "uowri",
 "iari",
 "yeeu",
 "oaji",
 "iowf",
 "oofi",
 "uwsu",
 "eefu",
 "ieex",
 "uows",
 "ooxi",
 "oawj",
 "ieeu",
 "uowr",
 "uyee",
 "uowf",
 "uwfa",
 "aajy",
 "iees",
 "uoos",
 "oori",
 "owfi",
 "iuwx",
 "iaso",
 "owsi",
 "uwra",
 "owri",
 "uaaj",
 "owji",
 "aasu",
 "ieef",
 "uwxu",
 "uaaf",
 "uwxa",
 "aasy",
 "uooi",
 "ooji",
 "uaar",
 "aaxu",
 "uoof",
 "uowj",
 "aaru",
 "aaju",
 "aafy",
 "ioos",
 "uwri",
 "uwsa",
 "uooj",
 "uowx",
 "aary",
 "uwja",
 "uaas",
 "iafu",
 "uees",
 "uwju",
 "uowi",
 "ieer",
 "iaaj",
 "iaay",
 "oasi",
 "oosi",
 "iori",
 "iaas",
 "uaax",
 "oari",
 "yees",
 "ueej",
 "oafi",
 "uasi",
 "aaxy",
 "ieej",
 "aafu",
 "oaws",
 "uwru",
 "eesu",
 "iawj",
 "oasy",
 "uwfu",
 "uoox",
 "iawf",
 "iar",
 "ajy",
 "aji",
 "ows",
 "aau",
 "ooj",
 "aro",
 "isa",
 "uaa",
 "oof",
 "uoo",
 "ori",
 "ooi",
 "uws",
 "ura",
 "ofa",
 "awj",
 "uwa",
 "eex",
 "uwu",
 "aso",
 "aaf",
 "uow",
 "iju",
 "awf",
 "ari",
 "afi",
 "ixa",
 "asu",
 "owf",
 "oaf",
 "uwj",
 "eso",
 "afu",
 "aws",
 "ary",
 "uwx",
 "ore",
 "oox",
 "oar",
 "ufa",
 "awr",
 "uas",
 "uee",
 "ury",
 "yee",
 "uys",
 "usi",
 "oas",
 "iao",
 "owr",
 "uwr",
 "oja",
 "efo",
 "axy",
 "ajo",
 "awx",
 "eer",
 "eeu",
 "iai",
 "ofi",
 "aas",
 "axi",
 "iaf",
 "ufi",
 "ora",
 "owx",
 "oos",
 "ios",
 "oxi",
 "ioj",
 "afy",
 "uaf",
 "uxi",
 "orf",
 "oor",
 "axo",
 "ufy",
 "iee",
 "usy",
 "aaj",
 "usa",
 "aar",
 "uar",
 "uyf",
 "ias",
 "uyx",
 "uji",
 "aay",
 "ujy",
 "ees",
 "ija",
 "asi",
 "asy",
 "oay",
 "osi",
 "eef",
 "uri",
 "iru",
 "iax",
 "oai",
 "ira",
 "uax",
 "ejo",
 "owi",
 "ues",
 "ius",
 "aax",
 "owj",
 "uyr",
 "ifa",
 "oax",
 "uya",
 "exo",
 "oaj",
 "uxy",
 "osa",
 "oaw",
 "uxa",
 "oji",
 "iof",
 "uwf",
 "uyj",
 "iow",
 "ero",
 "uaj",
 "afo",
 "oer",
 "uaw",
 "ior",
 "ieo",
 "eej",
 "oes",
 "iuj",
 "uja",
 "ngh",
 "ur",
 "ay",
 "eo",
 "oa",
 "ax",
 "ia",
 "ph",
 "ir",
 "kh",
 "ui",
 "gh",
 "of",
 "oo",
 "ng",
 "au",
 "es",
 "or",
 "yf",
 "ue",
 "oe",
 "oj",
 "tr",
 "yr",
 "ow",
 "ua",
 "af",
 "ix",
 "aj",
 "ij",
 "uj",
 "ef",
 "if",
 "ai",
 "oi",
 "os",
 "uf",
 "ch",
 "er",
 "ee",
 "ux",
 "uy",
 "is",
 "yx",
 "ar",
 "ao",
 "aw",
 "ej",
 "ys",
 "ox",
 "aa",
 "as",
 "uw",
 "dd",
 "iu",
 "us",
 "nh",
 "th",
 "ex",
 "o",
 "g",
 "x",
 "q",
 "d",
 "k",
 "a",
 "c",
 "u",
 "i",
 "f",
 "v",
 "p",
 "h",
 "m",
 "y",
 "b",
 "e",
 "r",
 "t",
 "l",
 "n",
 "s",
 NULL };

static const int cmu_viH_fv_000[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_001[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_002[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_003[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_004[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_005[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_006[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_007[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_008[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_009[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_010[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_011[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_012[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_013[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_014[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_015[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_016[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_017[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_018[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_019[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_020[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_021[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_022[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_023[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_024[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_025[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_026[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_027[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_028[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_029[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_030[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_031[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_032[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_033[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_034[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_035[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_036[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_037[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_038[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_039[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_040[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_041[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_042[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_043[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_044[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_045[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_046[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_047[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_048[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_049[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_050[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_051[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_052[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_053[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_054[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_055[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_056[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_057[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_058[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_059[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_060[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_061[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_062[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_063[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_064[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_065[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_066[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_067[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_068[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_069[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_070[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_071[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_072[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_073[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_074[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_075[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_076[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_077[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_078[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_079[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_080[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_081[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_082[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_083[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_084[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_085[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_086[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_087[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_088[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_089[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_090[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_091[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_092[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_093[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_094[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_095[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_096[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_097[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_098[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_099[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_100[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_101[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_102[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_103[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_104[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_105[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_106[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_107[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_108[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_109[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_110[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_111[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_112[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_113[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_114[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_115[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_116[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_117[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_118[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_119[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_120[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_121[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_122[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_123[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_124[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_125[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_126[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_127[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_128[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_129[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_130[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_131[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_132[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_133[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_134[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_135[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_136[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_137[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_138[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_139[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_140[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_141[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_142[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_143[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_144[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_145[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_146[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_147[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_148[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_149[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_150[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_151[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_152[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_153[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_154[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_155[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_156[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_157[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_158[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_159[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_160[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_161[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_162[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_163[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_164[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_165[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_166[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_167[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_168[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_169[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_170[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_171[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_172[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_173[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_174[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_175[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_176[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_177[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_178[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_179[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_180[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_181[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_182[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_183[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_184[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_185[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_186[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_187[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_188[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_189[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_190[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_191[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_192[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_193[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_194[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_195[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_196[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_197[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_198[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_199[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_200[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_201[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_202[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_203[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_204[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_205[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_206[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_207[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_208[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_209[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_210[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_211[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_212[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_213[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_214[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_215[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_216[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_217[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_218[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_219[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_220[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_221[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_222[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_223[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_224[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_225[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_226[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_227[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_228[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_229[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_230[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_231[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_232[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_233[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_234[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_235[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_236[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_237[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_238[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_239[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_240[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_241[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_242[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_243[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_244[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_245[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_246[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_247[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_248[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_249[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_250[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_251[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_252[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_253[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_254[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_255[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_256[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_257[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_258[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_259[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_260[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_261[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_262[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_263[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_264[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_265[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_266[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_267[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_268[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_269[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_270[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_271[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_272[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_273[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_274[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_275[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_276[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_277[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_278[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_279[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_280[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_281[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_282[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_283[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_284[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_285[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_286[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_287[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_288[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_289[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_290[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_291[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_292[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_293[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_294[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_295[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_296[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_297[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_298[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_299[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_300[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_301[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_302[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_303[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_304[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_305[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_306[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_307[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_308[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_309[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_310[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_311[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_312[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_313[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_314[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_315[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_316[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_317[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_318[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_319[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_320[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_viH_fv_321[] = { 0 };

static const int * const cmu_viH_fvtable[] = {
  cmu_viH_fv_000, 
  cmu_viH_fv_001, 
  cmu_viH_fv_002, 
  cmu_viH_fv_003, 
  cmu_viH_fv_004, 
  cmu_viH_fv_005, 
  cmu_viH_fv_006, 
  cmu_viH_fv_007, 
  cmu_viH_fv_008, 
  cmu_viH_fv_009, 
  cmu_viH_fv_010, 
  cmu_viH_fv_011, 
  cmu_viH_fv_012, 
  cmu_viH_fv_013, 
  cmu_viH_fv_014, 
  cmu_viH_fv_015, 
  cmu_viH_fv_016, 
  cmu_viH_fv_017, 
  cmu_viH_fv_018, 
  cmu_viH_fv_019, 
  cmu_viH_fv_020, 
  cmu_viH_fv_021, 
  cmu_viH_fv_022, 
  cmu_viH_fv_023, 
  cmu_viH_fv_024, 
  cmu_viH_fv_025, 
  cmu_viH_fv_026, 
  cmu_viH_fv_027, 
  cmu_viH_fv_028, 
  cmu_viH_fv_029, 
  cmu_viH_fv_030, 
  cmu_viH_fv_031, 
  cmu_viH_fv_032, 
  cmu_viH_fv_033, 
  cmu_viH_fv_034, 
  cmu_viH_fv_035, 
  cmu_viH_fv_036, 
  cmu_viH_fv_037, 
  cmu_viH_fv_038, 
  cmu_viH_fv_039, 
  cmu_viH_fv_040, 
  cmu_viH_fv_041, 
  cmu_viH_fv_042, 
  cmu_viH_fv_043, 
  cmu_viH_fv_044, 
  cmu_viH_fv_045, 
  cmu_viH_fv_046, 
  cmu_viH_fv_047, 
  cmu_viH_fv_048, 
  cmu_viH_fv_049, 
  cmu_viH_fv_050, 
  cmu_viH_fv_051, 
  cmu_viH_fv_052, 
  cmu_viH_fv_053, 
  cmu_viH_fv_054, 
  cmu_viH_fv_055, 
  cmu_viH_fv_056, 
  cmu_viH_fv_057, 
  cmu_viH_fv_058, 
  cmu_viH_fv_059, 
  cmu_viH_fv_060, 
  cmu_viH_fv_061, 
  cmu_viH_fv_062, 
  cmu_viH_fv_063, 
  cmu_viH_fv_064, 
  cmu_viH_fv_065, 
  cmu_viH_fv_066, 
  cmu_viH_fv_067, 
  cmu_viH_fv_068, 
  cmu_viH_fv_069, 
  cmu_viH_fv_070, 
  cmu_viH_fv_071, 
  cmu_viH_fv_072, 
  cmu_viH_fv_073, 
  cmu_viH_fv_074, 
  cmu_viH_fv_075, 
  cmu_viH_fv_076, 
  cmu_viH_fv_077, 
  cmu_viH_fv_078, 
  cmu_viH_fv_079, 
  cmu_viH_fv_080, 
  cmu_viH_fv_081, 
  cmu_viH_fv_082, 
  cmu_viH_fv_083, 
  cmu_viH_fv_084, 
  cmu_viH_fv_085, 
  cmu_viH_fv_086, 
  cmu_viH_fv_087, 
  cmu_viH_fv_088, 
  cmu_viH_fv_089, 
  cmu_viH_fv_090, 
  cmu_viH_fv_091, 
  cmu_viH_fv_092, 
  cmu_viH_fv_093, 
  cmu_viH_fv_094, 
  cmu_viH_fv_095, 
  cmu_viH_fv_096, 
  cmu_viH_fv_097, 
  cmu_viH_fv_098, 
  cmu_viH_fv_099, 
  cmu_viH_fv_100, 
  cmu_viH_fv_101, 
  cmu_viH_fv_102, 
  cmu_viH_fv_103, 
  cmu_viH_fv_104, 
  cmu_viH_fv_105, 
  cmu_viH_fv_106, 
  cmu_viH_fv_107, 
  cmu_viH_fv_108, 
  cmu_viH_fv_109, 
  cmu_viH_fv_110, 
  cmu_viH_fv_111, 
  cmu_viH_fv_112, 
  cmu_viH_fv_113, 
  cmu_viH_fv_114, 
  cmu_viH_fv_115, 
  cmu_viH_fv_116, 
  cmu_viH_fv_117, 
  cmu_viH_fv_118, 
  cmu_viH_fv_119, 
  cmu_viH_fv_120, 
  cmu_viH_fv_121, 
  cmu_viH_fv_122, 
  cmu_viH_fv_123, 
  cmu_viH_fv_124, 
  cmu_viH_fv_125, 
  cmu_viH_fv_126, 
  cmu_viH_fv_127, 
  cmu_viH_fv_128, 
  cmu_viH_fv_129, 
  cmu_viH_fv_130, 
  cmu_viH_fv_131, 
  cmu_viH_fv_132, 
  cmu_viH_fv_133, 
  cmu_viH_fv_134, 
  cmu_viH_fv_135, 
  cmu_viH_fv_136, 
  cmu_viH_fv_137, 
  cmu_viH_fv_138, 
  cmu_viH_fv_139, 
  cmu_viH_fv_140, 
  cmu_viH_fv_141, 
  cmu_viH_fv_142, 
  cmu_viH_fv_143, 
  cmu_viH_fv_144, 
  cmu_viH_fv_145, 
  cmu_viH_fv_146, 
  cmu_viH_fv_147, 
  cmu_viH_fv_148, 
  cmu_viH_fv_149, 
  cmu_viH_fv_150, 
  cmu_viH_fv_151, 
  cmu_viH_fv_152, 
  cmu_viH_fv_153, 
  cmu_viH_fv_154, 
  cmu_viH_fv_155, 
  cmu_viH_fv_156, 
  cmu_viH_fv_157, 
  cmu_viH_fv_158, 
  cmu_viH_fv_159, 
  cmu_viH_fv_160, 
  cmu_viH_fv_161, 
  cmu_viH_fv_162, 
  cmu_viH_fv_163, 
  cmu_viH_fv_164, 
  cmu_viH_fv_165, 
  cmu_viH_fv_166, 
  cmu_viH_fv_167, 
  cmu_viH_fv_168, 
  cmu_viH_fv_169, 
  cmu_viH_fv_170, 
  cmu_viH_fv_171, 
  cmu_viH_fv_172, 
  cmu_viH_fv_173, 
  cmu_viH_fv_174, 
  cmu_viH_fv_175, 
  cmu_viH_fv_176, 
  cmu_viH_fv_177, 
  cmu_viH_fv_178, 
  cmu_viH_fv_179, 
  cmu_viH_fv_180, 
  cmu_viH_fv_181, 
  cmu_viH_fv_182, 
  cmu_viH_fv_183, 
  cmu_viH_fv_184, 
  cmu_viH_fv_185, 
  cmu_viH_fv_186, 
  cmu_viH_fv_187, 
  cmu_viH_fv_188, 
  cmu_viH_fv_189, 
  cmu_viH_fv_190, 
  cmu_viH_fv_191, 
  cmu_viH_fv_192, 
  cmu_viH_fv_193, 
  cmu_viH_fv_194, 
  cmu_viH_fv_195, 
  cmu_viH_fv_196, 
  cmu_viH_fv_197, 
  cmu_viH_fv_198, 
  cmu_viH_fv_199, 
  cmu_viH_fv_200, 
  cmu_viH_fv_201, 
  cmu_viH_fv_202, 
  cmu_viH_fv_203, 
  cmu_viH_fv_204, 
  cmu_viH_fv_205, 
  cmu_viH_fv_206, 
  cmu_viH_fv_207, 
  cmu_viH_fv_208, 
  cmu_viH_fv_209, 
  cmu_viH_fv_210, 
  cmu_viH_fv_211, 
  cmu_viH_fv_212, 
  cmu_viH_fv_213, 
  cmu_viH_fv_214, 
  cmu_viH_fv_215, 
  cmu_viH_fv_216, 
  cmu_viH_fv_217, 
  cmu_viH_fv_218, 
  cmu_viH_fv_219, 
  cmu_viH_fv_220, 
  cmu_viH_fv_221, 
  cmu_viH_fv_222, 
  cmu_viH_fv_223, 
  cmu_viH_fv_224, 
  cmu_viH_fv_225, 
  cmu_viH_fv_226, 
  cmu_viH_fv_227, 
  cmu_viH_fv_228, 
  cmu_viH_fv_229, 
  cmu_viH_fv_230, 
  cmu_viH_fv_231, 
  cmu_viH_fv_232, 
  cmu_viH_fv_233, 
  cmu_viH_fv_234, 
  cmu_viH_fv_235, 
  cmu_viH_fv_236, 
  cmu_viH_fv_237, 
  cmu_viH_fv_238, 
  cmu_viH_fv_239, 
  cmu_viH_fv_240, 
  cmu_viH_fv_241, 
  cmu_viH_fv_242, 
  cmu_viH_fv_243, 
  cmu_viH_fv_244, 
  cmu_viH_fv_245, 
  cmu_viH_fv_246, 
  cmu_viH_fv_247, 
  cmu_viH_fv_248, 
  cmu_viH_fv_249, 
  cmu_viH_fv_250, 
  cmu_viH_fv_251, 
  cmu_viH_fv_252, 
  cmu_viH_fv_253, 
  cmu_viH_fv_254, 
  cmu_viH_fv_255, 
  cmu_viH_fv_256, 
  cmu_viH_fv_257, 
  cmu_viH_fv_258, 
  cmu_viH_fv_259, 
  cmu_viH_fv_260, 
  cmu_viH_fv_261, 
  cmu_viH_fv_262, 
  cmu_viH_fv_263, 
  cmu_viH_fv_264, 
  cmu_viH_fv_265, 
  cmu_viH_fv_266, 
  cmu_viH_fv_267, 
  cmu_viH_fv_268, 
  cmu_viH_fv_269, 
  cmu_viH_fv_270, 
  cmu_viH_fv_271, 
  cmu_viH_fv_272, 
  cmu_viH_fv_273, 
  cmu_viH_fv_274, 
  cmu_viH_fv_275, 
  cmu_viH_fv_276, 
  cmu_viH_fv_277, 
  cmu_viH_fv_278, 
  cmu_viH_fv_279, 
  cmu_viH_fv_280, 
  cmu_viH_fv_281, 
  cmu_viH_fv_282, 
  cmu_viH_fv_283, 
  cmu_viH_fv_284, 
  cmu_viH_fv_285, 
  cmu_viH_fv_286, 
  cmu_viH_fv_287, 
  cmu_viH_fv_288, 
  cmu_viH_fv_289, 
  cmu_viH_fv_290, 
  cmu_viH_fv_291, 
  cmu_viH_fv_292, 
  cmu_viH_fv_293, 
  cmu_viH_fv_294, 
  cmu_viH_fv_295, 
  cmu_viH_fv_296, 
  cmu_viH_fv_297, 
  cmu_viH_fv_298, 
  cmu_viH_fv_299, 
  cmu_viH_fv_300, 
  cmu_viH_fv_301, 
  cmu_viH_fv_302, 
  cmu_viH_fv_303, 
  cmu_viH_fv_304, 
  cmu_viH_fv_305, 
  cmu_viH_fv_306, 
  cmu_viH_fv_307, 
  cmu_viH_fv_308, 
  cmu_viH_fv_309, 
  cmu_viH_fv_310, 
  cmu_viH_fv_311, 
  cmu_viH_fv_312, 
  cmu_viH_fv_313, 
  cmu_viH_fv_314, 
  cmu_viH_fv_315, 
  cmu_viH_fv_316, 
  cmu_viH_fv_317, 
  cmu_viH_fv_318, 
  cmu_viH_fv_319, 
  cmu_viH_fv_320, 
 cmu_viH_fv_321 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"-");
DEF_STATIC_CONST_VAL_STRING(featval_1,"0");

static const cst_val * const cmu_viH_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 NULL };

const cst_phoneset cmu_viH_phoneset = {
  "cmu_viH",
  cmu_viH_featnames,
  cmu_viH_featvals,
  cmu_viH_phonenames,
  "pau",
  321,
  cmu_viH_fvtable,
  0  /* not freeable */
};
