/*******************************************************/
/**  Autogenerated cart trees for cmu_viH_pos    */
/*******************************************************/

#include "cst_string.h"
#include "cst_cart.h"
#include "cst_regex.h"
#include "cmu_viH_pos_cart.h"

static const cst_cart_node cmu_viH_pos_cart_nodes[] = {
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0000 },
{ 255, CST_CART_OP_NONE, 0, 0}};


static const char * const cmu_viH_pos_feat_table[] = {
NULL };

const cst_cart cmu_viH_pos_cart = {
  cmu_viH_pos_cart_nodes,
  cmu_viH_pos_feat_table
};
